---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: ttxt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ttxt 
  name: ttxt
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi