apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ttxt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ttxt 
  name: ttxt
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ttxt 
    weight: 100 
  wildcardPolicy: None
